<?php

use Illuminate\Database\Seeder;
use App\User;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      User::create(['email' => "admin@hsh.com",'email_verified_at' => now(),'password' => bcrypt('admin'),'remember_token' => Str::random(10),'tipo_de_usuario' => 0]);
      User::create(['name' => "Usuario Premium",'email' => "premium@hsh.com",'email_verified_at' => now(),'dni' => '12345678','password' => bcrypt('user'),'fecha_nac'=> '1990-04-25','direccion' => '8687 Schmidt Mall Suite 302v chneiderside, AK 98411-4359','telefono' =>'(626) 255-7313 x8563','semanas_disp' => 1,'solicito_upgrade' => true, 'pago_tipo' =>'Visa','pago_numero' => '2720656886308687','pago_cvv' => '658','pago_vencimiento' => '11/20','remember_token' => Str::random(10),'tipo_de_usuario' => 3]);
      User::create(['name' => "Usuario Estandar",'email' => "standard@hsh.com",'email_verified_at' => now(),'dni' => '12345679','password' => bcrypt('user'),'fecha_nac'=> '1990-04-25','direccion' => '8687 Schmidt Mall Suite 302v chneiderside, AK 98411-4359','telefono' =>'(626) 255-7313 x8563','semanas_disp' => 2,'solicito_upgrade' => false, 'pago_tipo' =>'Visa','pago_numero' => '2720656886308687','pago_cvv' => '658','pago_vencimiento' => '11/20','remember_token' => Str::random(10),'tipo_de_usuario' => 2]);
      User::create(['name' => "Usuario Sin verificar",'email' => "unverified@hsh.com",'email_verified_at' => now(),'dni' => '12345680','password' => bcrypt('user'),'fecha_nac'=> '1990-04-25','direccion' => '8687 Schmidt Mall Suite 302v chneiderside, AK 98411-4359','telefono' =>'(626) 255-7313 x8563','semanas_disp' => 0,'solicito_upgrade' => false, 'pago_tipo' =>'Visa','pago_numero' => '2720656886308687','pago_cvv' => '658','pago_vencimiento' => '11/20','remember_token' => Str::random(10),'tipo_de_usuario' => 1]);
      // factory(User::class)->times(15)->create();
      User::create(['name' => "Emmanuele Beltane Armenta Pareta",'direccion' => "Avenida Mourelos No. 732",'telefono' => '+54(141)-5112576', 'dni' => '31093068','fecha_nac' => '2000-01-03','email' => "lina_d@hotmail.com",'password' => bcrypt('password'),'email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "Daren Parry Rani",'direccion' => "Boulevard Valdez No. 865",'telefono' => '+54(050)-0668794','fecha_nac' => '1994-01-15','email' => "oina1@hotmail.com",'password' => bcrypt('password'),'dni' => '27623903','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "Amado Antonio López de Mota Rinaldi",'direccion' => "Real del Baudet No. 529",'telefono' => '+54(434)-7006144','fecha_nac' => '1987-04-10','email' => "helado21@hotmail.com",'password' => bcrypt('password'),'dni' => '37936634','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "Óscar De la Granja De la Colina",'direccion' => "Real del Rabat No. 362",'telefono' => '+54(848)-6336906','email' => "hddelacolina3@hotmail.com",'fecha_nac' => '1986-08-11','password' => bcrypt('password'),'dni' => '35538605','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "Mimount Cabiedas Shevchuk",'direccion' => "Boulevard Cotacachi No. 934",'telefono' => '+54(232)-4005632','email' => "hmshevchuk12@yopmail.com",'fecha_nac' => '1990-03-19','password' => bcrypt('password'),'dni' => '17170516','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "Lorena Arismendi Jaraquemada",'direccion' => "Taheri No. 941",'telefono' => '+54(030)-8117057','email' => "bblorena1@yopmail.com",'fecha_nac' => '1956-10-28','password' => bcrypt('password'),'dni' => '24719994','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "gvtorrento21@yopmail.com",'fecha_nac' => '1969-10-26','password' => bcrypt('password'),'dni' => '23717703','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "ut@dignissimlacusAliquam.ca",'fecha_nac' => '1975-11-15','password' => bcrypt('password'),'dni' => '28692724','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "et@gravida.com",'fecha_nac' => '2000-09-25','password' => bcrypt('password'),'dni' => '15424759','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "ipsum.sodales@ideratEtiam.org",'fecha_nac' => '1951-11-06','password' => bcrypt('password'),'dni' => '41304980','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "et.lacinia@maurissapiencursus.net",'fecha_nac' => '1985-08-25','password' => bcrypt('password'),'dni' => '16855390','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "Etiam@dolortempusnon.net",'fecha_nac' => '1993-12-24','password' => bcrypt('password'),'dni' => '31880759','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "gravida.Aliquam@Vestibulumante.org",'fecha_nac' => '1996-10-08','password' => bcrypt('password'),'dni' => '37423219','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "Proin.sed.turpis@sociisnatoque.org",'fecha_nac' => '1998-04-21','password' => bcrypt('password'),'dni' => '26298871','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "Vivamus.nisi.Mauris@non.net",'fecha_nac' => '1953-07-18','password' => bcrypt('password'),'dni' => '40754496','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "nisi.a@eleifendnon.net",'fecha_nac' => '1963-12-01','password' => bcrypt('password'),'dni' => '17058549','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "Aliquam.vulputate@id.co.uk",'fecha_nac' => '1991-02-15','password' => bcrypt('password'),'dni' => '24849857','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "Quisque.imperdiet@nibh.org",'fecha_nac' => '1985-06-22','password' => bcrypt('password'),'dni' => '27617377','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "diam.Duis.mi@orciPhasellus.edu",'fecha_nac' => '1983-02-12','password' => bcrypt('password'),'dni' => '16321738','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "vulputate@amet.ca",'fecha_nac' => '1976-07-25','password' => bcrypt('password'),'dni' => '26722915','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "sodales.purus.in@nibhenimgravida.ca",'fecha_nac' => '1966-09-19','password' => bcrypt('password'),'dni' => '10900962','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "Quisque.varius.Nam@non.co.uk",'fecha_nac' => '1972-04-01','password' => bcrypt('password'),'dni' => '26285079','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "dapibus.id@placerat.edu",'fecha_nac' => '1991-09-23','password' => bcrypt('password'),'dni' => '18776274','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "Donec.feugiat.metus@Sed.org",'fecha_nac' => '1975-12-09','password' => bcrypt('password'),'dni' => '33719671','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "Integer.mollis.Integer@necleo.net",'fecha_nac' => '1968-03-19','password' => bcrypt('password'),'dni' => '15411234','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "ut.aliquam.iaculis@scelerisquemollis.co.uk",'fecha_nac' => '1968-03-19','password' => bcrypt('password'),'dni' => '25052660','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "auctor@Quisque.org",'fecha_nac' => '1983-08-04','password' => bcrypt('password'),'dni' => '38054429','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "metus.In.lorem@Aliquamvulputate.ca",'fecha_nac' => '1974-09-10','password' => bcrypt('password'),'dni' => '10321336','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "non.massa.non@semvitaealiquam.ca",'fecha_nac' => '1963-01-01','password' => bcrypt('password'),'dni' => '12792855','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "tincidunt.congue@purusmauris.co.uk",'fecha_nac' => '1974-09-16','password' => bcrypt('password'),'dni' => '22132459','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "vel@leoVivamus.org",'fecha_nac' => '1982-09-12','password' => bcrypt('password'),'dni' => '35503129','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "morbi.tristique@enimmi.net",'fecha_nac' => '1950-11-03','password' => bcrypt('password'),'dni' => '21967434','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "nec.quam@tempor.edu",'fecha_nac' => '1956-05-28','password' => bcrypt('password'),'dni' => '27953119','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "pulvinar@risus.net",'fecha_nac' => '1952-01-21','password' => bcrypt('password'),'dni' => '12798861','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "tempus.lorem@elitafeugiat.ca",'fecha_nac' => '1999-08-21','password' => bcrypt('password'),'dni' => '18816623','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "facilisis.Suspendisse.commodo@eleifendCrassed.net",'fecha_nac' => '1981-09-30','password' => bcrypt('password'),'dni' => '40800623','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "neque.Nullam.ut@uterosnon.co.uk",'fecha_nac' => '1973-07-05','password' => bcrypt('password'),'dni' => '14874696','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "justo.Praesent@nibhlaciniaorci.org",'fecha_nac' => '1970-10-15','password' => bcrypt('password'),'dni' => '28723193','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "lacus.Aliquam.rutrum@loremfringilla.edu",'fecha_nac' => '1958-04-23','password' => bcrypt('password'),'dni' => '36689448','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
      User::create(['name' => "",'direccion' => "",'telefono' => '','email' => "eu.neque.pellentesque@tellusSuspendisse.edu",'fecha_nac' => '1975-08-09','password' => bcrypt('password'),'dni' => '15276727','email_verified_at' => now(),'remember_token' => Str::random(10),'tipo_de_usuario' => 3,'semanas_disp' => 2, 'pago_tipo' => "Visa", 'pago_numero' => 123456789876, 'pago_cvv' => 123, 'pago_vencimiento' => '01/20', 'solicito_upgrade' => 0]);
    }
}
